# Generated by Django 4.0.3 on 2022-04-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='photos/banners')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
