# Generated by Django 4.0.3 on 2022-04-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='accounts',
            new_name='account',
        ),
    ]
