# Generated by Django 4.0.3 on 2022-04-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default=0),
        ),
    ]
