# Generated by Django 4.0.3 on 2022-04-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/payments'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/shipments'),
        ),
    ]
