# Generated by Django 4.0.3 on 2022-04-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(),
        ),
    ]
